In [5]:
import numpy as np

In [2]:
np.__version__

'1.21.2'

In [8]:
# null matrix
a = np.zeros(shape=(2,5), dtype='int16')
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int16)

In [17]:
# memory size = no of element*memory size of each element
mem = a.size*a.itemsize
mem

20

In [35]:
# to get documentation
np.info(np.zeros)

zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------
zeros_lik

In [109]:
# create all zeros but fifth element is 4
a = np.zeros(10)
a[4] = 4
a

array([0., 0., 0., 0., 4., 0., 0., 0., 0., 0.])

In [110]:
# creting a vector with values from 10 to 49
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [111]:
# dimension of an array
a.ndim

1

In [54]:
# reversing an array
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [56]:
# make a 3x3 matrix
a = np.arange(0,9)
b = a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
# find the index of non zero elements
a = np.array([1,2,0,0,4,0])
np.nonzero(a)


(array([0, 1, 4], dtype=int64),)

In [68]:
# make an identity matrix of shape 3x3
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
# make a 3x3x3 matrix with random integer
a = np.random.randint(low=0, high=100, size=27)
a=a.reshape(3,3,3)
a

array([[[36, 63, 23],
        [65, 38, 88],
        [78, 96, 44]],

       [[52, 11, 69],
        [ 7, 54,  4],
        [66, 29, 19]],

       [[21,  1,  8],
        [26, 39, 66],
        [81, 66, 59]]])

In [84]:
# make a 3x3x3 matrix with random number
a = np.random.random(size=27)
a=a.reshape(3,3,3)
a

array([[[0.46232129, 0.64936391, 0.90859249],
        [0.84740193, 0.03234079, 0.22234896],
        [0.08574711, 0.8263261 , 0.76943131]],

       [[0.2369124 , 0.47028638, 0.88611186],
        [0.56814618, 0.89021128, 0.46397727],
        [0.89732817, 0.56307031, 0.2045044 ]],

       [[0.56013458, 0.55528451, 0.84515147],
        [0.03045643, 0.65460088, 0.97438181],
        [0.53725276, 0.46948272, 0.3937374 ]]])

In [91]:
# max and min in the array
a = np.random.random(size=100)
print(f'max is {a.max()} and min is {a.min()}')

max is 0.9896822916503407 and min is 0.009589343861341026


In [98]:
# mean ot the vector
a = np.random.randint(low=0, high=75, size=30)
a.mean()

38.93333333333333

In [124]:
# creating a 2D array
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
a = a.reshape(5,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [135]:
# creating a 2D array with 1's on boder and 2's inside
a = np.ones(20,dtype='int8')
a = a.reshape(5,4)
a[1:-1, 1:-1]=0
a

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]], dtype=int8)

In [6]:
# creating a matrix with padding
a = np.array([1,2,3,4])
a = a.reshape(2,2)
np.pad(a, 1,mode='constant')`

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])

In [55]:
# some unusual values
print(5 * np.nan)
print(np.nan == np.nan)
print(np.inf == np.inf)
print(np.inf > np.nan)
print(np.nan-np.nan)
print(0.3 == (3*0.1))


nan
False
True
False
nan
False


In [38]:
# crazy computer breakdown
3*0.1

0.30000000000000004

In [50]:
# diaggonal matrix, but the diagonal is shifted
a = np.diag([1,2,3,4],k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [74]:
# creating chess board like matrix
a = np.zeros((8,8),dtype=int)
a[1::2, ::2]=1
a[::2, 1::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [85]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element
print(np.unravel_index(335,(6,7,8)))

(5, 6, 7)


In [94]:
# create a matrix of shape 6,7,8 and find total num of elements
a = np.random.randint(10, size=(6,7,8))
a.size


336

In [4]:
# creating 8x8 matrix with tile methos
a = np.tile([1,2,3,4,5,6,7,8],8)
a = a.reshape(8,8)
a


array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [29]:
# normalize a mtrix ...hint: (x - min) / (max - min))
a = np.random.rand(5,5)
norm_a = a-a.min()/(a.max()-a.min())


In [30]:
a

array([[0.07591724, 0.72477187, 0.19157235, 0.21439402, 0.62129549],
       [0.73765075, 0.62705985, 0.68320448, 0.07385958, 0.2933818 ],
       [0.92007196, 0.64618933, 0.53539779, 0.21494911, 0.40510482],
       [0.00683506, 0.7148569 , 0.0041296 , 0.69687169, 0.08743534],
       [0.60237977, 0.89311538, 0.70625532, 0.87768183, 0.26060383]])

In [31]:
norm_a


array([[ 7.14086618e-02,  7.20263294e-01,  1.87063771e-01,
         2.09885444e-01,  6.16786918e-01],
       [ 7.33142176e-01,  6.22551274e-01,  6.78695899e-01,
         6.93510077e-02,  2.88873226e-01],
       [ 9.15563379e-01,  6.41680755e-01,  5.30889217e-01,
         2.10440529e-01,  4.00596248e-01],
       [ 2.32648687e-03,  7.10348319e-01, -3.78980310e-04,
         6.92363114e-01,  8.29267586e-02],
       [ 5.97871198e-01,  8.88606802e-01,  7.01746745e-01,
         8.73173249e-01,  2.56095252e-01]])

In [33]:
# Extra
'''
from sklearn.preprocessing import normalize
a_norm = normalize(a)
a_norm
'''


'\nfrom sklearn.preprocessing import normalize\na_norm = normalize(a)\na_norm\n'

In [34]:
# creating custom data type
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['red'])
type(color)


1


numpy.ndarray

In [63]:
# dot product
a = np.random.rand(5,3)
b = np.random.rand(3,2)
dot_pro = np.dot(a,b)
dot_pro


array([[0.50398294, 0.30047173],
       [1.39751828, 0.91281064],
       [1.20609348, 0.76367039],
       [0.61212196, 0.40521892],
       [0.75530195, 0.49742399]])

In [67]:
# create a random array and negate the values between 3 and 8
a = np.array(np.random.random(10)) 
a[(a>0.3) & (a<=0.8)]=0
a


array([0.        , 0.23871187, 0.        , 0.88178086, 0.1085523 ,
       0.        , 0.        , 0.83793135, 0.        , 0.        ])

In [75]:
# rounf off the elements of array
np.around(a*10, decimals=0)


array([0., 2., 0., 9., 1., 0., 0., 8., 0., 0.])

In [85]:
# These give different results
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [3]:
# which are legal ? Ans.All
Z=1
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

False

In [7]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan


C:\Users\Shaiz!!\AppData\Local\Temp/ipykernel_9936/623179752.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))


In [8]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[  8.  -5.   7.   7.  -5.   9. -10.  -5.   8.   9.]


In [9]:
Z1 = np.random.randint(0,10,10)

Z2 = np.random.randint(0,10,10)

print(np.intersect1d(Z1,Z2))

[0 1 2 6 9]


In [ ]:
defaults = np.seterr(all="ignore")

In [10]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Shaiz!!\AppData\Local\Temp/ipykernel_9936/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [12]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')

today = np.datetime64('today', 'D')

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday,today,tomorrow)

2022-07-22 2022-07-23 2022-07-24


In [13]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [14]:
A = np.ones(3)*1

B = np.ones(3)*2

C = np.ones(3)*3

np.add(A,B,out=B)

np.divide(A,2,out=A)

np.negative(A,out=A)

np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [15]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)

print (np.floor(Z))

print (np.ceil(Z)-1)

print (Z.astype(int))

print (np.trunc(Z))

[9. 0. 3. 3. 7. 1. 3. 3. 1. 8.]
[9. 0. 3. 3. 7. 1. 3. 3. 1. 8.]
[9. 0. 3. 3. 7. 1. 3. 3. 1. 8.]
[9 0 3 3 7 1 3 3 1 8]
[9. 0. 3. 3. 7. 1. 3. 3. 1. 8.]


In [16]:
Z = np.zeros((5,5))

Z += np.arange(5)

print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [18]:
def generate():
    for x in range(10):
        yield x

Z = np.fromiter(generate(),dtype=float,count=-1)

print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [19]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]

print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [20]:
Z = np.random.random(10)

Z.sort()

print(Z)

[0.16896453 0.36365664 0.44812421 0.52439449 0.55689151 0.56037508
 0.62640978 0.76468685 0.95689142 0.98161465]


In [21]:
Z = np.arange(10)

np.add.reduce(Z)

45

In [23]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)

print(equal)

equal = np.array_equal(A,B)

print(equal)

False
False


In [27]:
Z = np.zeros(10)

Z.flags.writeable = False
print(Z)
Z[0] = 1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: assignment destination is read-only

In [28]:
Z = np.random.random((10,2))

X,Y = Z[:,0], Z[:,1]

R = np.sqrt(X**2+Y**2)

T = np.arctan2(Y,X)

print(R)

print(T)

[0.85775464 1.07083453 0.95183588 0.17130786 1.13326516 0.58216088
 1.04780449 0.77536983 0.69408092 0.54474633]
[0.5022768  1.09362168 0.52556597 1.49510572 0.50201564 0.97781992
 0.51339773 1.01604011 1.007728   1.15976235]


In [29]:
Z = np.random.random(10)

Z[Z.argmax()] = 0

print(Z)

[0.13590249 0.20894433 0.58217696 0.         0.8089376  0.69271971
 0.12070977 0.41425848 0.59164814 0.94949688]


In [30]:
Z = np.zeros((5,5), [('x',float),('y',float)])

Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),

np.linspace(0,1,5))

print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [31]:
X = np.arange(8)

Y = X + 0.5

C = 1.0 / np.subtract.outer(X, Y)

print(np.linalg.det(C))

3638.163637117973


In [35]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [44]:
np.set_printoptions(threshold=float('inf'))

Z = np.zeros((16,16))

print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [45]:
Z = np.arange(100)

v = np.random.uniform(0,100)

index = (np.abs(Z-v)).argmin()

print(Z[index])

50


In [46]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),
            ('color', [ ('r', float, 1),('g', float, 1),('b', float, 1)])])

print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\Shaiz!!\AppData\Local\Temp/ipykernel_9936/484138045.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),


In [47]:
Z = np.random.random((10,2))

X,Y = np.atleast_2d(Z[:,0], Z[:,1])

D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)

print(D)

[[0.         0.80517167 0.22201241 0.47361873 0.31621448 0.62916446
  0.35455651 0.14896163 0.70004346 0.63387106]
 [0.80517167 0.         0.84981149 0.74366671 0.91082548 0.57630112
  0.50150648 0.65954766 0.5751062  0.43392347]
 [0.22201241 0.84981149 0.         0.29861317 0.09727183 0.51026083
  0.49822361 0.29751176 0.58164822 0.78606473]
 [0.47361873 0.74366671 0.29861317 0.         0.27544305 0.24433798
  0.58666936 0.46137389 0.30863515 0.84015057]
 [0.31621448 0.91082548 0.09727183 0.27544305 0.         0.51092929
  0.58966692 0.39327113 0.5794641  0.87629889]
 [0.62916446 0.57630112 0.51026083 0.24433798 0.51092929 0.
  0.60215079 0.56046331 0.07203377 0.79276081]
 [0.35455651 0.50150648 0.49822361 0.58666936 0.58966692 0.60215079
  0.         0.21187775 0.6557016  0.28827931]
 [0.14896163 0.65954766 0.29751176 0.46137389 0.39327113 0.56046331
  0.21187775 0.         0.627126   0.49818284]
 [0.70004346 0.5751062  0.58164822 0.30863515 0.5794641  0.07203377
  0.6557016  0.62712

In [48]:
Z = np.arange(10, dtype=np.int32)

Z = Z.astype(np.float32, copy=False)

print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [51]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')

Z = np.genfromtxt(s, delimiter=",", dtype=int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [52]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):
    print(index, value)

for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [53]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))

D = np.sqrt(X*X+Y*Y)

sigma, mu = 1.0, 0.0

G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )

print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [55]:
n = 10

p = 3

Z = np.zeros((n,n))

np.put(Z, np.random.choice(range(n*n), p, replace=False),1)

print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [56]:
X = np.random.rand(5, 10)

# Recent versions of numpy

Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy

Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.31809728  0.00678611 -0.0418543  -0.07426469 -0.14521299  0.25488819
  -0.12583249  0.10040717 -0.24711255 -0.04590173]
 [ 0.12035287  0.2729802   0.29865095 -0.2788078  -0.38192358 -0.41874177
   0.04880728  0.29374706  0.32582958 -0.28089479]
 [-0.16607143  0.09165088  0.28940098 -0.43464345  0.14849747  0.22033692
  -0.17623949  0.3395168  -0.01917492 -0.29327377]
 [-0.12230126  0.03881501  0.39330043  0.39922884  0.2203853   0.00579397
  -0.28979718  0.10515597 -0.302268   -0.44831306]
 [-0.1363568  -0.04026476 -0.3925807   0.43898952 -0.09487043  0.26583305
  -0.30344676  0.10644422 -0.24254149  0.39879416]]


In [57]:
Z = np.random.randint(0,10,(3,3))

print(Z)

print(Z[Z[:,1].argsort()])

[[2 7 9]
 [9 8 4]
 [7 9 0]]
[[2 7 9]
 [9 8 4]
 [7 9 0]]


In [58]:
Z = np.random.randint(0,3,(3,10))

print((~Z.any(axis=0)).any())

True


In [59]:
Z = np.random.uniform(0,1,10)

z = 0.5

m = Z.flat[np.abs(Z - z).argmin()]

print(m)

0.46946648490007936


In [61]:
A = np.arange(3).reshape(3,1)

B = np.arange(3).reshape(1,3)

it = np.nditer([A,B,None])

for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [67]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [69]:
Z = np.ones(10)

I = np.random.randint(0,len(Z),20)

Z += np.bincount(I, minlength=len(Z))

print(Z)

# np.add.at(Z, I, 1)
# print(Z)

[1. 4. 2. 2. 4. 3. 5. 3. 4. 2.]


In [70]:
X = [1,2,3,4,5,6]

I = [1,3,9,3,4,1]

F = np.bincount(I,X)

print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [71]:
w,h = 16,16

I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)

F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]

n = len(np.unique(F))

print(np.unique(I))

[0 1]


In [72]:
A = np.random.randint(0,10,(3,4,3,4))

sum = A.sum(axis=(-2,-1))

print(sum)

[[54 50 61 49]
 [59 49 47 54]
 [30 49 47 32]]


In [73]:
D = np.random.uniform(0,1,100)

S = np.random.randint(0,10,100)

D_sums = np.bincount(S, weights=D)

D_counts = np.bincount(S)

D_means = D_sums / D_counts

print(D_means)

# import pandas as pd
# print(pd.Series(D).groupby(S).mean())

[0.43949617 0.4884696  0.67856371 0.4876853  0.53483867 0.64101661
 0.43607762 0.53623319 0.7536544  0.56360505]


In [74]:
A = np.random.uniform(0,1,(5,5))

B = np.random.uniform(0,1,(5,5))

# Slow version

np.diag(np.dot(A, B))

# Fast version

np.sum(A * B.T, axis=1)

# Faster version

np.einsum("ij,ji->i", A, B)

array([1.54544981, 0.68181674, 2.13325884, 0.54170465, 1.61274211])

In [75]:
Z = np.array([1,2,3,4,5])

nz = 3

Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))

Z0[::nz+1] = Z

print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [76]:
A = np.ones((5,5,3))

B = 2*np.ones((5,5))

print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [77]:
A = np.arange(25).reshape(5,5)

A[[0,1]] = A[[1,0]]

print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [78]:
faces = np.random.randint(0,100,(10,3))

F = np.roll(faces.repeat(2,axis=1),-1,axis=1)

F = F.reshape(len(F)*3,2)

F = np.sort(F,axis=1)

G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )

G = np.unique(G)

print(G)

[( 1, 58) ( 1, 83) ( 4,  8) ( 4, 94) ( 6, 45) ( 6, 68) ( 8, 25) ( 8, 64)
 ( 8, 94) (11, 31) (11, 48) (16, 82) (16, 98) (25, 64) (26, 54) (26, 87)
 (28, 47) (28, 95) (30, 52) (30, 64) (31, 48) (45, 68) (47, 95) (52, 64)
 (54, 87) (58, 83) (61, 88) (61, 91) (82, 98) (88, 91)]


In [79]:
C = np.bincount([1,1,2,3,4,4,6])

A = np.repeat(np.arange(len(C)), C)

print(A)

[1 1 2 3 4 4 6]


In [80]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [81]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [82]:
Z = np.random.randint(0,2,100)

np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)

np.negative(Z, out=Z)

array([ 5.83733204e-01,  5.76671816e-01,  2.23460010e-01,  8.48909559e-01,
        2.62161632e-01, -5.13052875e-01, -4.81004105e-02, -4.39003073e-01,
       -1.56967239e-01,  7.09540633e-01, -8.11068707e-01,  2.61364244e-01,
        9.24035259e-03, -4.56238257e-01,  4.25529193e-01, -7.52525914e-01,
       -3.42659235e-01, -6.46215639e-01,  3.66657924e-01,  2.57333798e-02,
       -6.98952432e-01,  7.82597148e-01,  3.61772347e-01,  5.55288237e-01,
       -5.07307231e-01,  6.33402293e-01, -3.08100391e-01, -2.74757181e-01,
       -8.91051320e-01,  4.01728814e-01,  3.94421645e-01, -8.79966899e-01,
       -2.88489485e-01,  7.18209813e-01, -2.89141789e-04,  7.18062775e-01,
       -5.40114091e-01, -2.36349289e-01, -1.30850453e-01,  5.36862138e-01,
       -9.41551281e-01,  2.33158497e-01,  5.42765623e-01,  1.00733053e-01,
        3.58970586e-01,  1.96037204e-01, -9.84904393e-01,  6.56507767e-01,
        5.80488313e-01, -9.61526385e-03,  6.49932395e-01, -2.64652798e-01,
        5.93009438e-01,  

In [83]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[0.56045984 3.56299955 5.2244196  1.97374934 1.63452425 1.03622255
 9.76925153 2.60209308 3.09408475 8.27939178]


In [84]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[4.15017106e+00 9.87069350e+00 2.19869691e+00 4.76617587e+00
  3.18080107e+00 1.47351467e+00 3.46798511e+00 1.82448951e+00
  1.37795281e-01 7.18033035e+00]
 [7.62113465e+00 5.38121768e+00 8.22902022e+00 2.44871473e+00
  6.59758560e+00 1.11397506e+01 7.31075131e-01 7.78368575e+00
  3.82842432e+00 6.69394297e+00]
 [8.76460714e+00 4.91534604e+00 4.28062607e+00 1.00225682e+00
  7.77659010e+00 1.94490517e+00 4.96584490e+00 4.62890495e-01
  4.82731230e+00 2.57621437e+00]
 [8.04542279e+00 5.84940645e+00 2.09201436e+00 5.07161618e-01
  7.06883400e+00 7.19167387e-01 5.86272752e+00 2.49696114e+00
  4.06179091e+00 5.50342810e+00]
 [4.54884136e+00 8.55678548e+00 4.81663482e+00 9.25081088e-01
  3.53118973e+00 1.04938209e+01 2.59285100e+00 8.27052576e+00
  7.32631863e-01 5.31849547e+00]
 [9.03229738e+00 4.39852327e+00 6.32803205e+00 2.20242213e+00
  8.03111420e+00 5.16543814e+00 3.44990014e+00 2.19953636e+00
  5.14847175e+00 8.24196435e-01]
 [5.55698747e+00 7.35732061e+00 7.08372051e+00 7.76101549e

In [85]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[2 4 1 1 9 5 9 3 9 7]
 [5 7 8 2 5 6 8 7 8 8]
 [2 7 0 5 2 0 0 1 6 6]
 [3 6 6 7 5 2 3 7 5 3]
 [5 6 9 4 6 7 4 4 1 2]
 [7 0 1 4 1 6 0 1 9 5]
 [1 5 3 7 6 3 2 1 3 0]
 [0 5 9 2 9 3 3 9 9 7]
 [5 7 8 8 0 4 0 4 5 0]
 [2 9 2 6 8 3 2 4 5 3]]
[[0 0 0 0 0]
 [0 2 4 1 1]
 [0 5 7 8 2]
 [0 2 7 0 5]
 [0 3 6 6 7]]


C:\Users\Shaiz!!\AppData\Local\Temp/ipykernel_9936/1159162857.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


In [86]:
Z = np.arange(1,15,dtype=np.uint32)

R = stride_tricks.as_strided(Z,(11,4),(4,4))

print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [87]:
Z = np.random.uniform(0,1,(10,10))

U, S, V = np.linalg.svd(Z) # Singular Value Decomposition

rank = np.sum(S > 1e-10)

print(rank)

10


In [88]:
Z = np.random.randint(0,10,50)

print(np.bincount(Z).argmax())

0


In [89]:
Z = np.random.randint(0,5,(10,10))

n = 3

i = 1 + (Z.shape[0]-3)

j = 1 + (Z.shape[1]-3)

C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)

print(C)

[[[[4 3 1]
   [0 2 1]
   [0 3 2]]

  [[3 1 0]
   [2 1 3]
   [3 2 4]]

  [[1 0 3]
   [1 3 0]
   [2 4 3]]

  [[0 3 4]
   [3 0 3]
   [4 3 3]]

  [[3 4 3]
   [0 3 2]
   [3 3 4]]

  [[4 3 4]
   [3 2 0]
   [3 4 2]]

  [[3 4 2]
   [2 0 2]
   [4 2 0]]

  [[4 2 2]
   [0 2 0]
   [2 0 1]]]


 [[[0 2 1]
   [0 3 2]
   [0 0 4]]

  [[2 1 3]
   [3 2 4]
   [0 4 4]]

  [[1 3 0]
   [2 4 3]
   [4 4 2]]

  [[3 0 3]
   [4 3 3]
   [4 2 3]]

  [[0 3 2]
   [3 3 4]
   [2 3 2]]

  [[3 2 0]
   [3 4 2]
   [3 2 1]]

  [[2 0 2]
   [4 2 0]
   [2 1 0]]

  [[0 2 0]
   [2 0 1]
   [1 0 1]]]


 [[[0 3 2]
   [0 0 4]
   [1 1 1]]

  [[3 2 4]
   [0 4 4]
   [1 1 1]]

  [[2 4 3]
   [4 4 2]
   [1 1 0]]

  [[4 3 3]
   [4 2 3]
   [1 0 4]]

  [[3 3 4]
   [2 3 2]
   [0 4 3]]

  [[3 4 2]
   [3 2 1]
   [4 3 2]]

  [[4 2 0]
   [2 1 0]
   [3 2 0]]

  [[2 0 1]
   [1 0 1]
   [2 0 0]]]


 [[[0 0 4]
   [1 1 1]
   [0 0 2]]

  [[0 4 4]
   [1 1 1]
   [0 2 3]]

  [[4 4 2]
   [1 1 0]
   [2 3 0]]

  [[4 2 3]
   [1 0 4]
   [3 0 3]]

  [[2 3 2]
   

In [90]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 6  1 11  1  8]
 [ 1  5  6 10 10]
 [11  6  1 42  5]
 [ 1 10 42  8  9]
 [ 8 10  5  9  5]]


In [91]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [96]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [97]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
  0 0 0 0 0 0 0 0 0 0 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
  1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
  1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1

In [98]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


In [99]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [100]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [101]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.17 s ± 53 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
630 ms ± 32.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
377 ms ± 4.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [102]:

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 5 6]


In [103]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[4 1 0]
 [4 1 4]
 [4 2 2]
 [4 3 4]
 [0 2 4]
 [0 0 0]
 [4 4 1]
 [3 4 2]
 [4 1 4]
 [1 4 3]]
[[4 1 0]
 [4 1 4]
 [4 2 2]
 [4 3 4]
 [0 2 4]
 [4 4 1]
 [3 4 2]
 [4 1 4]
 [1 4 3]]


In [104]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [105]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [106]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 1 0]
 [1 1 1]]


In [107]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.25810267, 0.85557223, 0.62445643, 0.52445609, 0.69816117,
        0.28032786, 0.28913801, 0.48181246, 0.26037428, 0.16569115],
       [0.19780445, 0.65569253, 0.47857025, 0.4019321 , 0.53505601,
        0.21483736, 0.22158928, 0.36925092, 0.19954537, 0.1269822 ],
       [0.10245482, 0.3396226 , 0.24788032, 0.20818481, 0.27713769,
        0.11127719, 0.11477442, 0.19125726, 0.10335655, 0.06577172],
       [0.20530585, 0.68055856, 0.49671922, 0.41717469, 0.5553471 ,
        0.22298471, 0.22999268, 0.38325414, 0.20711279, 0.13179779],
       [0.01688782, 0.05598063, 0.04085858, 0.03431549, 0.04568112,
        0.01834203, 0.01891848, 0.03152529, 0.01703645, 0.01084128],
       [0.14715733, 0.4878048 , 0.35603405, 0.29901882, 0.39805683,
        0.15982902, 0.16485214, 0.27470554, 0.14845249, 0.09446886],
       [0.04190587, 0.13891176, 0.10138752, 0.08515134, 0.11335431,
        0.04551438, 0.0469448 , 0.07822767, 0.04227469, 0.02690182],
       [0.10261076, 0.34013952, 0.2482576

In [108]:

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [109]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [110]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.30088049  0.11199122]
